# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to Webserver

on:
  push:
    branches: [ "Deployed" ]
  pull_request:
    branches: [ "Deployed" ]

jobs:
  build:

    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./romdrop.com/
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'romdrop.com/package-lock.json'
    - name: Install dependencies
      run: npm ci
    - name: Building source code
      run: npm run build
    - name: Commit build to main branch
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automatic Building website

        # Optional. Options used by `git-commit`.
        # See https://git-scm.com/docs/git-commit#_options
        # Optional. Options used by `git-push`.
        # See https://git-scm.com/docs/git-push#_options
        push_options: '--force'
    - name: Create new release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GH_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Deployment archive"
    - name: Deploy release to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PW }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /romdrop.com/
          set -e
          rm -rf latest
          curl -LO https://github.com/matthijsvrenswoude/romdrop.com/archive/refs/tags/latest.zip
          unzip latest.zip
          rm latest.zip
      env:
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

